Hosting static frontend files in prod NEXT
In production NEXT, the frontend's code is now statically generated
and is being served on NGINX proxy instead of having its own client
docker container.

Please update your nginx.conf file accordingly to take in these new
changes.

This commit also cleans up code and documentation based on our old
way of using/updating swagger documentation.

Signed-off-by: Michael Nguyen <michael.nguyen79@t-mobile.com>

diff --git a/bin/start b/bin/start
--- a/bin/start
+++ b/bin/start
@@ -95,6 +95,11 @@ if [[ "$PROD" == "1" ]]; then
         echo "nginx.conf file not found. Creating one from nginx.conf-example ..."
         cp ./nginx.conf-example ./nginx.conf
     fi
+    if ! [ -e client/build/ ]
+    then
+        echo "Client build folder is missing, please run ./bin/build_client first."
+        exit 1
+    fi
 else
     CMD="$CMD -f docker-compose.override.yaml"
 fi
